---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: cv-latex.tex
geometry: margin=.7in

title: "Resume"
author: Mike Konczal

fontawesome: yes
email: konczal@gmail.com
github: mtkonczal
web: www.mikekonczal.com
twitter: mtkonczal
city_name: Takoma Park, MD
#phone: "+1 234 567 8999"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---
\pagenumbering{arabic}
# Professional Summary

Accomplished researcher, writer, and advocate skilled in economic data and policy analysis. I have been cited in over 300 press articles, testified before Congress four times, and made over 50 media appearances on platforms like *CBS Sunday Morning* and *Washington Journal*. My written work has been featured in esteemed publications such as *The New York Times* and *The Washington Post*.

# Experience 

**Chief Economist and Special Assistant to the President for Economic Policy,** White House National Economic Council, Washington DC \hfill 2024

- Provided ongoing economic analysis for the National Economic Advisor and support for NEC Deputy Director for fiscal and macroeconomic policy, including on inflation, growth, employment, tax, budget, and housing policy.

- Developed strategic arguments for the President’s economic policy agenda, in close consultation with colleagues at the Treasury Department and the Council of Economic Advisers.

- Led the formulation of the White House’s messaging following all macroeconomic data releases, including themes, statements, charts, and talking points. Tracked the process for data releases, created internal NEC measures, and directed rapid analyses and responses on indicators.

- Amplified the economic messaging of the White House and National Economic Advisor, via speechwriting, content development, and media interaction. Regularly engaged external economic validators, experts, reporters, and academics on economic data as well as the President’s agenda.

**Director,** Roosevelt Institute, New York, NY \hfill 2010 - 2023

- Directed the macroeconomic research team, providing original research on key economic issues, including inflation, growth, and employment, at a leading think tank. Served as a go-to expert on economic and policy issues for journalists and policymakers.

- Authored over 20 white papers and edited four comprehensive report volumes. Automated real-time data analysis with R and Python across major data releases. Collaborated with the communications team to devise engagement strategies for our projects, and government relations to work with elected officials and other policymakers.

- Orchestrated four multi-year research and policy initiatives as an expert on topics including the Dodd-Frank Act, the Great Recession, economic inequality, and evolving economic paradigms. Managed teams of two internal researchers and three external fellows.

- Successfully secured and managed research grants from organizations such as the Kauffman, Ford, and Hewlett Foundations, as well as Open Philanthropy.

**Financial Engineer,** Moody’s KMV, San Francisco, CA\hfill 2007 - 2009

- Developed testing benchmarks for Moody’s KMV credit risk model, recognized as the 2006 "Top Provider in Trading and Banking" by Risk Magazine. Collaborated on five system releases of RiskFrontier software, developing test cases and acceptance criteria for cutting-edge credit risk modeling algorithms.

- Actively participated in discussions on various approaches to credit risk modeling, focusing on the Vasicek-Kealhofer (VK) model derived from the Black-Scholes-Merton framework. Contributed to debates on capital requirements and loss reserving.

- Prototyped research algorithms using R, SAS, Matlab, and Excel VB to replicate results. Designed and implemented a system that automated the collection, storage, and analysis of significant data sets across four releases, reducing test execution time by 40 percent.

**Senior Test Engineer,** Motorola, Schaumburg, IL \hfill 2001-2005

- Directed performance, load, and stress testing across four major iDEN system releases, earning a Motorola BRAVO Award for "above and beyond performance contribution." Designed automated Six Sigma-level test cases using Perl, Python, and MySQL based on models of consumer behavior. Trained six employees in testing methods.

# Education

**M.S. Finance, University of Illinois at Urbana-Champaign** \hfill 2007

- Completed coursework in the graduate-level economics sequence, covering microeconomics, macroeconomics, and econometrics.

- Conducted advanced research in finance, including research replication on large data sets like Compustat, using R and SAS. Modeled option valuation using binomial tree, Monte Carlo, and finite difference methods in C++.

**B.A. Mathematics and Computer Science, University of Illinois at Urbana-Champaign** \hfill 2001

- Focused coursework in Probability, Statistics, Data Structures, Graph Theory, Numerical Methods, and Nonlinear Programming.

# Media Appearances and Writings

## Quotes and Media Mentions##
- Highly experienced in media engagement, cited in over 300 articles and media references.
- Top Outlets: _New York Times_ (32), _Washington Post_ (23), _Vox_ (21), _Bloomberg_ (10), _Business Insider_ (9), and more.

## Published Writing
- Contributed articles to many publications, including but not limited to: _The Nation_ (19 articles), _Dissent_ (7), _Vox_ (6), _Boston Review_ (5), and the _New York Times_ (2).
- Published the book _Freedom From the Market_ (New Press, 2021), highlighted as a "Summer Book of 2021" in the economics category by the _Financial Times_. Reviews include: _Democracy Journal_, _Foreign Policy_, _Foreign Affairs_, _Wall Street Journal_, and _National Review_.
- Co-authored *Rewriting the Rules of the American Economy* (W.W. Norton, 2015), with Nobel laureate Joseph Stiglitz, summarizing the latest research in inequality.

## Media Appearances
- Garnered significant media presence with over 25 podcast appearances and 15 TV interviews, and amassed a following of over 50,000 on Twitter.
- Notable Appearances: _The Weeds_ podcast (4 times), _Planet Money_ (3), _Washington Journal_ (2), _CNBC_ (2), _CBS Sunday Morning_, and _The Rachel Maddow Show_.

\newpage

# Books

_Freedom From the Market: America’s Fight to Liberate Itself from the Grip of the Invisible Hand._ New York: New Press, 2021.

- Named a "Summer Books of 2021: Economics" by Martin Wolf of the _Financial Times_.
- Listed among "The Best Political Economy Books of 2021" by Promarket, The Stigler Center at the University of Chicago.
- Reviews include _Democracy Journal_, _Foreign Policy_, _Foreign Affairs_, _Wall Street Journal_, and _National Review_.

_Rewriting the Rules of the American Economy: An Agenda for Growth and Shared Prosperity._ With Joseph Stiglitz, Nell Abernathy, Adam Hersh, and Susan Holmberg. New York: W.W. Norton, 2015.

# Testimony

["Inflation: A Preventable Crisis."](https://rooseveltinstitute.org/publications/inflation-in-2023-causes-progress-and-solutions/) Testimony before the House Committee on Oversight and Accountability Subcommittee on Health Care and Financial Services, March 9, 2023.

["Power and Profiteering: How Certain Industries Hiked Prices, Fleeced Consumers, and Drove Inflation."](https://rooseveltinstitute.org/wp-content/uploads/2022/09/RI_MikeKonczal_HouseTestimony_202209.pdf) Testimony before the House Committee on Oversight and Reform, Subcommittee on Economic and Consumer Policy, September 22, 2022.

["Lending in a Crisis: Reviewing the Federal Reserve’s Emergency Lending Powers During the Pandemic and Examining Proposals to Address Future Economic Crises."](https://rooseveltinstitute.org/wp-content/uploads/2021/09/mkonczal-testimony-Fed-lending-facilities-09_23.pdf) Testimony before the Subcommittee on National Security, International Development and Monetary Policy, House Committee on Financial Services, September 23, 2021.

[“The Impact of Regulations on Short-Term Financing.”](https://financialservices.house.gov/uploadedfiles/12.08.2016_michael_konczal_testimony.pdf) Testimony before the Subcommittee on Capital Markets and Government Sponsored Enterprises, House Committee on Financial Services, December 8th, 2016.

# Select Research Papers

[_Supply-Side Expansion Has Driven the Decline in Inflation._](https://rooseveltinstitute.org/publications/supply-side-expansion-has-driven-the-decline-in-inflation/) Roosevelt Institute, September 2023.

- Coverage: [_New York Times_](https://www.nytimes.com/2023/09/11/opinion/inflation-unemployment-phillips-recession.html), [_Planet Money_](https://www.npr.org/2023/09/14/1197954105/the-indicator-from-planet-money-draft-09-14-2023), [_The Economist_](https://www.economist.com/finance-and-economics/2024/01/10/has-team-transitory-really-won-americas-inflation-debate), [_Bloomberg_](https://www.bloomberg.com/news/newsletters/2024-01-29/five-things-you-need-to-know-to-start-your-day-americas).

[_Prices, Profits, and Power: An Analysis of 2021 Firm-Level Markups._](https://rooseveltinstitute.org/publications/prices-profits-and-power/) With Niko Lusiani. Roosevelt Institute, June 2022.

- Coverage: [_New York Times_](https://www.nytimes.com/2022/06/22/opinion/inflation-corporate-profits.html), [_Insider_](https://www.businessinsider.com/inflation-rising-prices-corporate-profits-markups-surging-record-pace-study-2022-6).

[_A New Direction for the Federal Reserve: Expanding the Monetary Policy Toolkit._](https://rooseveltinstitute.org/publications/federal-reserve-expanding-monetary-policy-toolkit/) With J.W. Mason. Roosevelt Institute, November 2017.

- Coverage: [_Financial Times_](https://www.ft.com/content/5318501e-67a1-38a6-bcdd-fb2545ec33fa), [Macro Musings Podcast](https://macromusings.libsyn.com/94-mike-konczal-on-expanding-the-feds-monetary-toolkit), [_New York Magazine_](https://nymag.com/intelligencer/2019/07/aoc-is-making-monetary-policy-cool-and-political-again.html).

[_Declining Entrepreneurship, Labor Mobility, and Business Dynamism: A Demand-Side Approach._](https://rooseveltinstitute.org/publications/declining-entrepreneurship-labor-mobility-business-dynamism/) With Marshall Steinbaum. Roosevelt Institute, July 2016.

- Coverage: [_Wall Street Journal_](https://www.wsj.com/articles/what-if-there-just-arent-enough-jobs-to-go-around-1469206183), [_Politico_](https://www.politico.com/agenda/story/2016/10/americas-innovation-crisis-000222/), [_The Economist_](https://www.economist.com/finance-and-economics/2016/07/28/a-hire-power).

# Editor

[_Untamed: How to Check Corporate, Financial, and Monopoly Power._](https://rooseveltinstitute.org/publications/untamed-corporate-financial-monopoly-power/) With Nell Abernathy and Katy Milani. Roosevelt Institute, June 2016.

[_An Unfinished Mission: Making Wall Street Work for Us._](https://5000ff5f-c81e-4025-9f29-a8526ec49666.usrfiles.com/ugd/5000ff_d2d1ebec20fc466c94f319d3014ce00a.pdf) With Americans for Financial Reform, November 2013.

_Will It Work? How Will We Know? The Future of Financial Reform._ Roosevelt Institute, October 2010.

_Make Markets Be Markets._ Roosevelt Institute, March 2010.

# Columnist

_The Nation_, Economics Columnist.\hfill 2014 - current  

_Dissent_, Editorial Board.\hfill 2015 - current  

_Vox, The Big Idea_, Monthly Columnist.\hfill 2017-2018  

_Washington Post, Wonkblog_, Weekly Columnist.\hfill 2013-2014

# Select Op-Eds

["How to Have a Roaring 2020s (Without Wild Inflation).”](https://www.nytimes.com/2021/06/15/opinion/inflation-economy-infrastructure.html) With J.W. Mason. _New York Times_, June 15, 2021.

[”Why a Biden Administration Needs to Spend Big.”](https://www.thenation.com/article/economy/deficit-spending-budget/) _The Nation_. November 2, 2020.

[“Democrats Must Become The Party Of Freedom.”](https://talkingpointsmemo.com/feature/democrats-must-become-the-party-of-freedom) With Nell Abernathy. _Talking Points Memo_, November 2018.

[“Why are Democrats Helping Trump Dismantle Dodd-Frank?”](https://www.nytimes.com/2018/03/06/opinion/democrats-trump-dodd-frank.html) _New York Times_, March 6th, 2018.

["The G.O.P. Plan to Unleash Wall Street."](https://www.nytimes.com/2017/06/09/opinion/the-gop-plan-to-unleash-wall-street.html) _New York Times_, June 9, 2017.

[“Frenzied Financialization.”](https://washingtonmonthly.com/2014/11/03/frenzied-financialization/) _Washington Monthly_, December 1st, 2014.

[“The Voluntarism Fantasy.”](https://democracyjournal.org/magazine/32/the-voluntarism-fantasy/) _Democracy Journal_, March 1st, 2014.

# Select Talks and Interviews

["Are Corporate Profits Driving Inflation?"](https://www.cbsnews.com/video/are-corporate-profits-driving-inflation/) _CBS Sunday Morning_, July 10th, 2022.

"Why Freedom Requires Keeping Us Free From the Market." The Havens Wright Center for Social Justice, University of Wisconsin, Madison, October 14, 2021.

["The Federal Reserve's regulatory issues."](https://www.stitcher.com/show/voxs-the-weeds/episode/the-federal-reserves-regulatory-issues-86696425) _Vox's The Weeds_ podcast, September 10, 2021.

["Freedom From Markets."](https://www.stitcher.com/show/voxs-the-weeds/episode/freedom-from-markets-81017167) _Vox's The Weeds_ podcast, January 22, 2021.

“Will the Coronavirus Relief Bill Prevent a Great Depression?” Hammer Museum, April 22nd, 2020.

["LOLOLoligarchy."](https://www.stitcher.com/show/lovett-or-leave-it/episode/lolololigarchy-54731277) _Pod Save America: Lovett or Leave It_ podcast. June 1, 2018.

["How the GOP is weaponizing the tax code."](https://www.stitcher.com/show/voxs-the-weeds/episode/how-the-gop-is-weaponizing-the-tax-code-52422516) _Vox's The Weeds_ podcast, December 1, 2017.

“Is California’s 15 Minimum Wage Law a Good Idea?” USD Center for Ethics, Economics, and Public Policy, September 22nd, 2016

“Let’s Re-imagine the Rules.” Aggie Agora, Texas A&M University, March 1st, 2016.